import '../models/event_model.dart';

/// A single keyword→category mapping with all display and behavioural fields.
class CategoryRule {
  const CategoryRule({
    required this.keyword,
    required this.categoryId,
    required this.emoji,
    required this.primaryColor,
    required this.bgColor,
    this.recurrence = EventRecurrence.once,
    this.reminderDays = const <int>[0],
    this.baseScore = 1.0,
    this.secondaryCategories = const <String>[],
  });

  /// Lowercase keyword to match against the normalised title.
  final String keyword;
  final String categoryId;
  final String emoji;
  final int primaryColor;

  /// Background tint for the suggestion banner.
  final int bgColor;
  final EventRecurrence recurrence;
  final List<int> reminderDays;

  /// Base confidence score (0.0–1.0). Multiplied by match-type multiplier.
  final double baseScore;

  /// Other categories this event may also belong to (multi-label).
  final List<String> secondaryCategories;
}

/// Synonym / alias → canonical keyword, applied before the main lookup.
const Map<String, String> kAliasMap = <String, String>{
  // ── Birthday
  'bday': 'birthday',
  'b-day': 'birthday',
  'birth day': 'birthday',

  // ── Anniversary (misspellings + compound forms)
  'anniv': 'anniversary',
  'annivers': 'anniversary',
  'aniversary': 'anniversary',   // single-n typo
  'anniversay': 'anniversary',   // missing-r typo
  'aniversay': 'anniversary',    // double typo
  'anniversery': 'anniversary',  // e→ery typo
  'anniverssary': 'anniversary', // double-s typo
  'anniversarie': 'anniversary', // French-influenced typo
  // Compound anniversary aliases → routed to specific compound rules
  'job anniversary': 'work anniversary',
  'career anniversary': 'work anniversary',
  'employment anniversary': 'work anniversary',
  'company anniversary': 'work anniversary',
  'office anniversary': 'work anniversary',
  'cycling anniversary': 'bike anniversary',
  'motorbike anniversary': 'bike anniversary',
  'bicycle anniversary': 'bike anniversary',

  // ── Travel
  'hols': 'holiday',
  'vacay': 'vacation',
  'trekking': 'trek',
  'hiking': 'trek',
  'hike': 'trek',
  'outing': 'trip',
  'excursion': 'trip',

  // ── Health & Wellness
  'quitting': 'quit',
  'sobriety': 'sober',
  'sobriety anniversary': 'sober anniversary',
  'clean anniversary': 'sober anniversary',

  // ── Finance
  'paycheck': 'salary',
  'payday': 'salary',
  'wages': 'salary',
  'mortgage': 'loan',

  // ── Education
  'grad': 'graduation',
  'commencement': 'graduation',

  // ── Personal / Seasonal
  'xmas': 'christmas',
  'nye': 'new year',
  'mum': "mom's",
  'mama': "mom's",
  'papa': "dad's",

  // ── Home
  'relocation': 'moving',
  'relocating': 'moving',

  // ── Fitness
  'spinning': 'workout',
  'lifting': 'gym',
  'weight training': 'gym',
  'hiit': 'workout',

  // ── Pet
  'gotcha day': 'adoption',
  'pet birthday': 'adoption',

  // ── Vehicle
  'driving license': 'driving licence',
  'license': 'licence',
  'motorbike': 'motorcycle',
  'moto': 'motorcycle',

  // ── Entertainment
  'karaoke night': 'karaoke',
  'gig': 'concert',
  'recital': 'concert',
  'show': 'concert',
  'live music': 'concert',
  'music night': 'concert',

  // ── Food / Grooming
  'haircut': 'hair cut',
  'bbq': 'barbecue',
  'cookout': 'barbecue',
  'date night': 'dinner date',

  // ── Misc
  'meetup': 'reunion',
  'hangout': 'party',
};

/// Master rule list — drives all Smart Event Creation suggestions.
const List<CategoryRule> kEventRules = <CategoryRule>[

  // ── Birthday ────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'birthday', categoryId: 'Birthday', emoji: '🎂',
      primaryColor: 0xFFE91E63, bgColor: 0x1AE91E63,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: "mom's birthday", categoryId: 'Birthday', emoji: '🎂',
      primaryColor: 0xFFE91E63, bgColor: 0x1AE91E63,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: "dad's birthday", categoryId: 'Birthday', emoji: '🎂',
      primaryColor: 0xFFE91E63, bgColor: 0x1AE91E63,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: 'sweet sixteen', categoryId: 'Birthday', emoji: '🎂',
      primaryColor: 0xFFE91E63, bgColor: 0x1AE91E63,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),

  // ── Anniversary ─────────────────────────────────────────────────────────
  CategoryRule(keyword: 'anniversary', categoryId: 'Anniversary', emoji: '💑',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'wedding anniversary', categoryId: 'Anniversary', emoji: '💍',
      primaryColor: 0xFFAD1457, bgColor: 0x1AAD1457,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'wedding', categoryId: 'Anniversary', emoji: '💍',
      primaryColor: 0xFFAD1457, bgColor: 0x1AAD1457,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'marriage', categoryId: 'Anniversary', emoji: '💍',
      primaryColor: 0xFFF50057, bgColor: 0x1AF50057,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 0.9),
  CategoryRule(keyword: 'marriage anniversary', categoryId: 'Anniversary', emoji: '💍',
      primaryColor: 0xFFF50057, bgColor: 0x1AF50057,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'valentine', categoryId: 'Anniversary', emoji: '❤️',
      primaryColor: 0xFFE53935, bgColor: 0x1AE53935,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: 'engagement', categoryId: 'Anniversary', emoji: '💍',
      primaryColor: 0xFFE91E63, bgColor: 0x1AE91E63,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone', 'Personal']),
  CategoryRule(keyword: 'first date anniversary', categoryId: 'Anniversary', emoji: '💑',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'relationship anniversary', categoryId: 'Anniversary', emoji: '💑',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone']),

  // ── Travel ──────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'trip', categoryId: 'Travel', emoji: '✈️',
      primaryColor: 0xFF2196F3, bgColor: 0x1A2196F3,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'travel', categoryId: 'Travel', emoji: '✈️',
      primaryColor: 0xFF2196F3, bgColor: 0x1A2196F3,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'vacation', categoryId: 'Travel', emoji: '🏖️',
      primaryColor: 0xFF00BCD4, bgColor: 0x1A00BCD4,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'flight', categoryId: 'Travel', emoji: '🛫',
      primaryColor: 0xFF1976D2, bgColor: 0x1A1976D2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'cruise', categoryId: 'Travel', emoji: '🚢',
      primaryColor: 0xFF0288D1, bgColor: 0x1A0288D1,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'holiday', categoryId: 'Travel', emoji: '🌴',
      primaryColor: 0xFF00BCD4, bgColor: 0x1A00BCD4,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'trek', categoryId: 'Travel', emoji: '🏔️',
      primaryColor: 0xFF3F51B5, bgColor: 0x1A3F51B5,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      baseScore: 0.9, secondaryCategories: <String>['Fitness']),
  CategoryRule(keyword: 'backpacking', categoryId: 'Travel', emoji: '🎒',
      primaryColor: 0xFF2196F3, bgColor: 0x1A2196F3,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'road trip', categoryId: 'Travel', emoji: '🚗',
      primaryColor: 0xFF1976D2, bgColor: 0x1A1976D2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),

  // ── Health ──────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'doctor', categoryId: 'Health', emoji: '🩺',
      primaryColor: 0xFF4CAF50, bgColor: 0x1A4CAF50,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'hospital', categoryId: 'Health', emoji: '🏥',
      primaryColor: 0xFF66BB6A, bgColor: 0x1A66BB6A,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'dentist', categoryId: 'Health', emoji: '🦷',
      primaryColor: 0xFF66BB6A, bgColor: 0x1A66BB6A,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'surgery', categoryId: 'Health', emoji: '🏥',
      primaryColor: 0xFFF44336, bgColor: 0x1AF44336,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'checkup', categoryId: 'Health', emoji: '🩺',
      primaryColor: 0xFF4CAF50, bgColor: 0x1A4CAF50,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'therapy', categoryId: 'Health', emoji: '🧠',
      primaryColor: 0xFF26A69A, bgColor: 0x1A26A69A,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'medication', categoryId: 'Health', emoji: '💊',
      primaryColor: 0xFF66BB6A, bgColor: 0x1A66BB6A,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'vaccine', categoryId: 'Health', emoji: '💉',
      primaryColor: 0xFF4CAF50, bgColor: 0x1A4CAF50,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: 'sober', categoryId: 'Health', emoji: '🧘',
      primaryColor: 0xFF26C6DA, bgColor: 0x1A26C6DA,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone', 'Habit']),
  CategoryRule(keyword: 'sober anniversary', categoryId: 'Health', emoji: '🏆',
      primaryColor: 0xFF26C6DA, bgColor: 0x1A26C6DA,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Habit', 'Anniversary']),
  CategoryRule(keyword: 'clean anniversary', categoryId: 'Health', emoji: '🌟',
      primaryColor: 0xFF26C6DA, bgColor: 0x1A26C6DA,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Habit', 'Anniversary']),
  CategoryRule(keyword: 'quit smoking', categoryId: 'Health', emoji: '🚭',
      primaryColor: 0xFF26C6DA, bgColor: 0x1A26C6DA,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone', 'Habit']),
  CategoryRule(keyword: 'quit', categoryId: 'Health', emoji: '🚭',
      primaryColor: 0xFF26C6DA, bgColor: 0x1A26C6DA,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      baseScore: 0.65, secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'optician', categoryId: 'Health', emoji: '👁️',
      primaryColor: 0xFF4CAF50, bgColor: 0x1A4CAF50,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'blood test', categoryId: 'Health', emoji: '🩸',
      primaryColor: 0xFFF44336, bgColor: 0x1AF44336,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),

  // ── Fitness ─────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'gym', categoryId: 'Fitness', emoji: '🏋️',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Habit']),
  CategoryRule(keyword: 'workout', categoryId: 'Fitness', emoji: '🏃',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Habit']),
  CategoryRule(keyword: 'fitness', categoryId: 'Fitness', emoji: '💪',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Habit']),
  CategoryRule(keyword: 'marathon', categoryId: 'Fitness', emoji: '🏅',
      primaryColor: 0xFF388E3C, bgColor: 0x1A388E3C,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'half marathon', categoryId: 'Fitness', emoji: '🏅',
      primaryColor: 0xFF388E3C, bgColor: 0x1A388E3C,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'race', categoryId: 'Fitness', emoji: '🏁',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'yoga', categoryId: 'Fitness', emoji: '🧘',
      primaryColor: 0xFF26A69A, bgColor: 0x1A26A69A,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Habit']),
  CategoryRule(keyword: 'cycling', categoryId: 'Fitness', emoji: '🚴',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Habit']),
  CategoryRule(keyword: 'swimming', categoryId: 'Fitness', emoji: '🏊',
      primaryColor: 0xFF0288D1, bgColor: 0x1A0288D1,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Habit']),
  CategoryRule(keyword: 'started gym', categoryId: 'Fitness', emoji: '🏋️',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone', 'Habit']),
  CategoryRule(keyword: 'running', categoryId: 'Fitness', emoji: '🏃',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      baseScore: 0.9, secondaryCategories: <String>['Habit']),
  CategoryRule(keyword: 'pilates', categoryId: 'Fitness', emoji: '🧘',
      primaryColor: 0xFF26A69A, bgColor: 0x1A26A69A,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Habit']),
  CategoryRule(keyword: 'crossfit', categoryId: 'Fitness', emoji: '💪',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Habit']),

  // ── Work ────────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'deadline', categoryId: 'Work', emoji: '⏰',
      primaryColor: 0xFFFF9800, bgColor: 0x1AFF9800,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 3]),
  CategoryRule(keyword: 'meeting', categoryId: 'Work', emoji: '📌',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'interview', categoryId: 'Work', emoji: '🎤',
      primaryColor: 0xFF7B1FA2, bgColor: 0x1A7B1FA2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 3],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'launch', categoryId: 'Work', emoji: '🚀',
      primaryColor: 0xFFFF5722, bgColor: 0x1AFF5722,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'conference', categoryId: 'Work', emoji: '🏢',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'project', categoryId: 'Work', emoji: '🚀',
      primaryColor: 0xFFFF9800, bgColor: 0x1AFF9800,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      baseScore: 0.9),
  CategoryRule(keyword: 'promotion', categoryId: 'Work', emoji: '🎉',
      primaryColor: 0xFFFF9800, bgColor: 0x1AFF9800,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'new job', categoryId: 'Work', emoji: '💼',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'first day', categoryId: 'Work', emoji: '💼',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'last day', categoryId: 'Work', emoji: '👋',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'presentation', categoryId: 'Work', emoji: '📊',
      primaryColor: 0xFFFF9800, bgColor: 0x1AFF9800,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  // ── Work anniversaries (baseScore 1.1 so they beat the generic 'anniversary' rule)
  CategoryRule(keyword: 'work anniversary', categoryId: 'Work', emoji: '💼',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'job anniversary', categoryId: 'Work', emoji: '💼',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'career anniversary', categoryId: 'Work', emoji: '🏆',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  // ── Extra work rules
  CategoryRule(keyword: 'office', categoryId: 'Work', emoji: '🏢',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      baseScore: 0.75),
  CategoryRule(keyword: 'work from home', categoryId: 'Work', emoji: '💻',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'remote work', categoryId: 'Work', emoji: '💻',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'appraisal', categoryId: 'Work', emoji: '📊',
      primaryColor: 0xFFFF9800, bgColor: 0x1AFF9800,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: 'performance review', categoryId: 'Work', emoji: '📋',
      primaryColor: 0xFFFF9800, bgColor: 0x1AFF9800,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: 'bonus', categoryId: 'Work', emoji: '💰',
      primaryColor: 0xFF4CAF50, bgColor: 0x1A4CAF50,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Finance']),
  CategoryRule(keyword: 'internship', categoryId: 'Work', emoji: '📋',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'resignation', categoryId: 'Work', emoji: '🚪',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'team outing', categoryId: 'Work', emoji: '🏅',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'workshop', categoryId: 'Work', emoji: '🛠️',
      primaryColor: 0xFFFF9800, bgColor: 0x1AFF9800,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'hackathon', categoryId: 'Work', emoji: '💻',
      primaryColor: 0xFF9C27B0, bgColor: 0x1A9C27B0,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'training', categoryId: 'Work', emoji: '📚',
      primaryColor: 0xFFFF9800, bgColor: 0x1AFF9800,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      baseScore: 0.85),

  // ── Finance ─────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'salary', categoryId: 'Finance', emoji: '💰',
      primaryColor: 0xFF009688, bgColor: 0x1A009688,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[1, 3]),
  CategoryRule(keyword: 'first salary', categoryId: 'Finance', emoji: '💰',
      primaryColor: 0xFF009688, bgColor: 0x1A009688,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'rent', categoryId: 'Finance', emoji: '🏠',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[1, 3]),
  CategoryRule(keyword: 'bill', categoryId: 'Finance', emoji: '💸',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[1, 3]),
  CategoryRule(keyword: 'loan', categoryId: 'Finance', emoji: '🏦',
      primaryColor: 0xFF37474F, bgColor: 0x1A37474F,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[1, 3]),
  CategoryRule(keyword: 'tax', categoryId: 'Finance', emoji: '📊',
      primaryColor: 0xFF455A64, bgColor: 0x1A455A64,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[1, 3, 7]),
  CategoryRule(keyword: 'investment', categoryId: 'Finance', emoji: '📈',
      primaryColor: 0xFF009688, bgColor: 0x1A009688,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[1]),
  CategoryRule(keyword: 'insurance', categoryId: 'Finance', emoji: '🛡️',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[1, 7]),
  CategoryRule(keyword: 'subscription', categoryId: 'Finance', emoji: '💳',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[1, 3]),
  CategoryRule(keyword: 'emi', categoryId: 'Finance', emoji: '🏦',
      primaryColor: 0xFF37474F, bgColor: 0x1A37474F,
      recurrence: EventRecurrence.monthly, reminderDays: <int>[1, 3]),

  // ── Education ───────────────────────────────────────────────────────────
  CategoryRule(keyword: 'exam', categoryId: 'Education', emoji: '📝',
      primaryColor: 0xFF7B1FA2, bgColor: 0x1A7B1FA2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 3]),
  CategoryRule(keyword: 'graduation', categoryId: 'Education', emoji: '🎓',
      primaryColor: 0xFF673AB7, bgColor: 0x1A673AB7,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'course', categoryId: 'Education', emoji: '📚',
      primaryColor: 0xFF7B1FA2, bgColor: 0x1A7B1FA2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      baseScore: 0.9),
  CategoryRule(keyword: 'school', categoryId: 'Education', emoji: '🏫',
      primaryColor: 0xFF3F51B5, bgColor: 0x1A3F51B5,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      baseScore: 0.9),
  CategoryRule(keyword: 'college', categoryId: 'Education', emoji: '🎓',
      primaryColor: 0xFF673AB7, bgColor: 0x1A673AB7,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'university', categoryId: 'Education', emoji: '🏛️',
      primaryColor: 0xFF673AB7, bgColor: 0x1A673AB7,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'scholarship', categoryId: 'Education', emoji: '🎓',
      primaryColor: 0xFF673AB7, bgColor: 0x1A673AB7,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'result', categoryId: 'Education', emoji: '📋',
      primaryColor: 0xFF7B1FA2, bgColor: 0x1A7B1FA2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      baseScore: 0.75),

  // ── Milestone ───────────────────────────────────────────────────────────
  CategoryRule(keyword: 'milestone', categoryId: 'Milestone', emoji: '🏆',
      primaryColor: 0xFFFFC107, bgColor: 0x1AFFC107,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'achievement', categoryId: 'Milestone', emoji: '🏆',
      primaryColor: 0xFFFFC107, bgColor: 0x1AFFC107,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'first time', categoryId: 'Milestone', emoji: '🌟',
      primaryColor: 0xFFFFC107, bgColor: 0x1AFFC107,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'record', categoryId: 'Milestone', emoji: '🎯',
      primaryColor: 0xFFFFC107, bgColor: 0x1AFFC107,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      baseScore: 0.7),

  // ── Home ────────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'house', categoryId: 'Home', emoji: '🏠',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'apartment', categoryId: 'Home', emoji: '🏢',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'moving', categoryId: 'Home', emoji: '📦',
      primaryColor: 0xFF8D6E63, bgColor: 0x1A8D6E63,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'renovation', categoryId: 'Home', emoji: '🔨',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'warming', categoryId: 'Home', emoji: '🏡',
      primaryColor: 0xFF6D4C41, bgColor: 0x1A6D4C41,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'purchase', categoryId: 'Home', emoji: '🔑',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      baseScore: 0.6, secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'new home', categoryId: 'Home', emoji: '🏡',
      primaryColor: 0xFF6D4C41, bgColor: 0x1A6D4C41,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  // ── Home anniversaries
  CategoryRule(keyword: 'home anniversary', categoryId: 'Home', emoji: '🏡',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'house anniversary', categoryId: 'Home', emoji: '🏠',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'apartment anniversary', categoryId: 'Home', emoji: '🏢',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),

  // ── Vehicle ─────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'car', categoryId: 'Vehicle', emoji: '🚗',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'bike', categoryId: 'Vehicle', emoji: '🏍️',
      primaryColor: 0xFF546E7A, bgColor: 0x1A546E7A,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'motorcycle', categoryId: 'Vehicle', emoji: '🏍️',
      primaryColor: 0xFF546E7A, bgColor: 0x1A546E7A,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'scooter', categoryId: 'Vehicle', emoji: '🛵',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'truck', categoryId: 'Vehicle', emoji: '🚛',
      primaryColor: 0xFF546E7A, bgColor: 0x1A546E7A,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'driving licence', categoryId: 'Vehicle', emoji: '🪪',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'car service', categoryId: 'Vehicle', emoji: '🔧',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 7]),
  CategoryRule(keyword: 'insurance renewal', categoryId: 'Vehicle',
      emoji: '🛡️', primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[1, 7]),
  CategoryRule(keyword: 'new car', categoryId: 'Vehicle', emoji: '🚗',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'new bike', categoryId: 'Vehicle', emoji: '🏍️',
      primaryColor: 0xFF546E7A, bgColor: 0x1A546E7A,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  // ── Vehicle anniversaries (baseScore 1.1 beats generic 'anniversary' and 'bike'/'car')
  CategoryRule(keyword: 'bike anniversary', categoryId: 'Vehicle', emoji: '🏍️',
      primaryColor: 0xFF546E7A, bgColor: 0x1A546E7A,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'car anniversary', categoryId: 'Vehicle', emoji: '🚗',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'motorcycle anniversary', categoryId: 'Vehicle', emoji: '🏍️',
      primaryColor: 0xFF546E7A, bgColor: 0x1A546E7A,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'scooter anniversary', categoryId: 'Vehicle', emoji: '🛵',
      primaryColor: 0xFF607D8B, bgColor: 0x1A607D8B,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),

  // ── Pet ─────────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'dog', categoryId: 'Pet', emoji: '🐶',
      primaryColor: 0xFFFF8F00, bgColor: 0x1AFF8F00,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'cat', categoryId: 'Pet', emoji: '🐱',
      primaryColor: 0xFFFF8F00, bgColor: 0x1AFF8F00,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'pet', categoryId: 'Pet', emoji: '🐾',
      primaryColor: 0xFFFF6F00, bgColor: 0x1AFF6F00,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'adoption', categoryId: 'Pet', emoji: '🐾',
      primaryColor: 0xFFFF6F00, bgColor: 0x1AFF6F00,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'puppy', categoryId: 'Pet', emoji: '🐶',
      primaryColor: 0xFFFF8F00, bgColor: 0x1AFF8F00,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'kitten', categoryId: 'Pet', emoji: '🐱',
      primaryColor: 0xFFFF8F00, bgColor: 0x1AFF8F00,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'rabbit', categoryId: 'Pet', emoji: '🐰',
      primaryColor: 0xFFFF8F00, bgColor: 0x1AFF8F00,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'parrot', categoryId: 'Pet', emoji: '🦜',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'vet', categoryId: 'Pet', emoji: '🐾',
      primaryColor: 0xFFFF6F00, bgColor: 0x1AFF6F00,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  // ── Pet anniversaries
  CategoryRule(keyword: 'pet anniversary', categoryId: 'Pet', emoji: '🐾',
      primaryColor: 0xFFFF6F00, bgColor: 0x1AFF6F00,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'dog anniversary', categoryId: 'Pet', emoji: '🐶',
      primaryColor: 0xFFFF8F00, bgColor: 0x1AFF8F00,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),
  CategoryRule(keyword: 'cat anniversary', categoryId: 'Pet', emoji: '🐱',
      primaryColor: 0xFFFF8F00, bgColor: 0x1AFF8F00,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7],
      baseScore: 1.1, secondaryCategories: <String>['Milestone', 'Anniversary']),

  // ── Habit ───────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'habit', categoryId: 'Habit', emoji: '🔄',
      primaryColor: 0xFF00ACC1, bgColor: 0x1A00ACC1,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0]),
  CategoryRule(keyword: 'streak', categoryId: 'Habit', emoji: '🔥',
      primaryColor: 0xFFFF5722, bgColor: 0x1AFF5722,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'meditation', categoryId: 'Habit', emoji: '🧘',
      primaryColor: 0xFF26A69A, bgColor: 0x1A26A69A,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0]),
  CategoryRule(keyword: 'reading', categoryId: 'Habit', emoji: '📖',
      primaryColor: 0xFF5E35B1, bgColor: 0x1A5E35B1,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      baseScore: 0.85),
  CategoryRule(keyword: 'journaling', categoryId: 'Habit', emoji: '📓',
      primaryColor: 0xFF7E57C2, bgColor: 0x1A7E57C2,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0]),
  CategoryRule(keyword: 'diet', categoryId: 'Habit', emoji: '🥗',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Health']),
  CategoryRule(keyword: 'fasting', categoryId: 'Habit', emoji: '🍽️',
      primaryColor: 0xFF26A69A, bgColor: 0x1A26A69A,
      recurrence: EventRecurrence.weekly, reminderDays: <int>[0],
      secondaryCategories: <String>['Health']),
  CategoryRule(keyword: 'no alcohol', categoryId: 'Habit', emoji: '🚫',
      primaryColor: 0xFF26C6DA, bgColor: 0x1A26C6DA,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      secondaryCategories: <String>['Health', 'Milestone']),

  // ── Personal ────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'party', categoryId: 'Personal', emoji: '🥳',
      primaryColor: 0xFFFF5722, bgColor: 0x1AFF5722,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: 'christmas', categoryId: 'Personal', emoji: '🎄',
      primaryColor: 0xFF388E3C, bgColor: 0x1A388E3C,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: 'new year', categoryId: 'Personal', emoji: '🎉',
      primaryColor: 0xFFFF6F00, bgColor: 0x1AFF6F00,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'concert', categoryId: 'Personal', emoji: '🎵',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'karaoke', categoryId: 'Personal', emoji: '🎤',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'singing', categoryId: 'Personal', emoji: '🎤',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1],
      baseScore: 0.85),
  CategoryRule(keyword: 'music show', categoryId: 'Personal', emoji: '🎸',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'live music', categoryId: 'Personal', emoji: '🎶',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'theatre', categoryId: 'Personal', emoji: '🎭',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'theater', categoryId: 'Personal', emoji: '🎭',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'movie', categoryId: 'Personal', emoji: '🎬',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'cinema', categoryId: 'Personal', emoji: '🎥',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'game night', categoryId: 'Personal', emoji: '🎮',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'sports game', categoryId: 'Personal', emoji: '⚽',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'sports match', categoryId: 'Personal', emoji: '🏆',
      primaryColor: 0xFF43A047, bgColor: 0x1A43A047,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'baby', categoryId: 'Personal', emoji: '👶',
      primaryColor: 0xFFFF80AB, bgColor: 0x1AFF80AB,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7],
      secondaryCategories: <String>['Milestone']),
  CategoryRule(keyword: 'festival', categoryId: 'Personal', emoji: '🎆',
      primaryColor: 0xFFFF6F00, bgColor: 0x1AFF6F00,
      recurrence: EventRecurrence.yearly, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'reunion', categoryId: 'Personal', emoji: '🤝',
      primaryColor: 0xFF5E6AD2, bgColor: 0x1A5E6AD2,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1, 7]),
  CategoryRule(keyword: 'dinner date', categoryId: 'Personal', emoji: '❤️',
      primaryColor: 0xFFE91E63, bgColor: 0x1AE91E63,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'hair cut', categoryId: 'Personal', emoji: '💇',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),

  // ── Food ────────────────────────────────────────────────────────────────
  CategoryRule(keyword: 'dinner', categoryId: 'Food', emoji: '🍽️',
      primaryColor: 0xFFFF7043, bgColor: 0x1AFF7043,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'restaurant', categoryId: 'Food', emoji: '🍴',
      primaryColor: 0xFFFF7043, bgColor: 0x1AFF7043,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'lunch', categoryId: 'Food', emoji: '🥗',
      primaryColor: 0xFFFF8A65, bgColor: 0x1AFF8A65,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'brunch', categoryId: 'Food', emoji: '🥞',
      primaryColor: 0xFFFF8A65, bgColor: 0x1AFF8A65,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'barbecue', categoryId: 'Food', emoji: '🍖',
      primaryColor: 0xFFFF7043, bgColor: 0x1AFF7043,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
  CategoryRule(keyword: 'breakfast', categoryId: 'Food', emoji: '🍳',
      primaryColor: 0xFFFF8A65, bgColor: 0x1AFF8A65,
      recurrence: EventRecurrence.once, reminderDays: <int>[0]),
  CategoryRule(keyword: 'coffee', categoryId: 'Food', emoji: '☕',
      primaryColor: 0xFF795548, bgColor: 0x1A795548,
      recurrence: EventRecurrence.once, reminderDays: <int>[0],
      baseScore: 0.75),
  CategoryRule(keyword: 'food festival', categoryId: 'Food', emoji: '🎪',
      primaryColor: 0xFFFF7043, bgColor: 0x1AFF7043,
      recurrence: EventRecurrence.once, reminderDays: <int>[0, 1]),
];
