import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'app/app.dart';
import 'core/hive_boxes.dart';
import 'features/events/models/event_model.dart';
import 'features/habits/models/habit_model.dart';
import 'features/notifications/notification_service.dart';
// Generated by `flutterfire configure` — do not edit manually.
// ignore: depend_on_referenced_packages
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();
  if (!Hive.isAdapterRegistered(1)) {
    Hive.registerAdapter(EventModelAdapter());
  }
  if (!Hive.isAdapterRegistered(2)) {
    Hive.registerAdapter(HabitModelAdapter());
  }

  await Future.wait(<Future<void>>[
    Hive.openBox<EventModel>(HiveBoxes.events),
    Hive.openBox<HabitModel>(HiveBoxes.habits),
    Hive.openBox<dynamic>(HiveBoxes.settings),
    Hive.openBox<dynamic>(HiveBoxes.categories),
    Hive.openBox<dynamic>(HiveBoxes.syncMeta),
  ]);

  // Firebase initialised with platform-specific options generated by
  // `flutterfire configure`. This ensures Google Sign-In works on Android
  // (correct OAuth client IDs, SHA-1, etc.) and prevents ApiException 10.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (_) {
    // Intentionally ignored to keep guest mode/offline mode functional.
  }

  final NotificationService notifications = NotificationService();
  await notifications.initialize();

  runApp(const ProviderScope(child: EventCounterApp()));
}
