import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'app/app.dart';
import 'core/hive_boxes.dart';
import 'features/events/models/event_model.dart';
import 'features/habits/models/habit_model.dart';
import 'features/notifications/notification_service.dart';
// Generated by `flutterfire configure` — do not edit manually.
// ignore: depend_on_referenced_packages
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  String? startupError;
  try {
    await Future.wait<void>(<Future<void>>[
      _initializeLocalStorage(),
      _initializeFirebase(),
    ]);
  } catch (error, stackTrace) {
    debugPrint('Startup initialization failed: $error');
    debugPrintStack(stackTrace: stackTrace);
    startupError = error.toString();
  }

  runApp(
    ProviderScope(
      child: EventCounterApp(startupError: startupError),
    ),
  );

  if (startupError == null) {
    // Keep startup snappy by moving notification bootstrapping off the
    // critical path; these can run shortly after first frame.
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      try {
        final NotificationService notifications = NotificationService();
        await notifications.initialize();
        await notifications.requestPermissionsOnFirstLaunch();
        await notifications.scheduleTodayEventsNotification();
        if (Hive.isBoxOpen(HiveBoxes.events)) {
          final List<EventModel> existingEvents =
              Hive.box<EventModel>(HiveBoxes.events).values.toList(growable: false);
          await notifications.showLiveEventNotification(existingEvents);
        }
      } catch (e) {
        debugPrint('Post-frame notification setup failed: $e');
      }
    });
  }
}

Future<void> _initializeLocalStorage() async {
  await Hive.initFlutter();

  if (!Hive.isAdapterRegistered(1)) {
    Hive.registerAdapter(EventModelAdapter());
  }
  if (!Hive.isAdapterRegistered(2)) {
    Hive.registerAdapter(HabitModelAdapter());
  }

  await Future.wait<void>(<Future<void>>[
    _openHiveBox<EventModel>(HiveBoxes.events),
    _openHiveBox<HabitModel>(HiveBoxes.habits),
    _openHiveBox<dynamic>(HiveBoxes.settings),
    _openHiveBox<dynamic>(HiveBoxes.categories),
    _openHiveBox<dynamic>(HiveBoxes.syncMeta),
  ]);
}

Future<void> _initializeFirebase() async {
  // Firebase initialised with platform-specific options generated by
  // `flutterfire configure`. This ensures Google Sign-In works on Android
  // (correct OAuth client IDs, SHA-1, etc.) and prevents ApiException 10.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    ).timeout(const Duration(seconds: 10));
  } catch (_) {
    // Intentionally ignored to keep guest mode/offline mode functional.
  }
}

Future<void> _openHiveBox<T>(String boxName) async {
  try {
    await Hive.openBox<T>(boxName).timeout(const Duration(seconds: 6));
  } catch (error) {
    throw StateError('Failed to open local data box "$boxName": $error');
  }
}
